In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('datasets/02_cc_traning.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  object
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  object
 8   Contract Length    440832 non-null  object
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), object(3)
memory usage: 40.4+ MB

In [5]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [7]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

What is Normalization?

Normalization is a scaling technique in which values are shifted and rescaled so that they end up ranging between 0 and 1. It is also known as Min-Max scaling.

What is Standardization?

Standardization is another scaling technique where the values are centered around the mean with a unit standard deviation. This means that the mean of the attribute becomes zero and the resultant distribution has a unit standard deviation.

In [11]:
df.describe().round(2)

,CustomerID,Age,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn
count,440832.00,440832.00,440832.00,440832.00,440832.00,440832.00,440832.00,440832.00,440832.00
mean,225398.67,39.37,31.26,15.81,3.60,12.97,631.62,14.48,0.57
std,129531.92,12.44,17.26,8.59,3.07,8.26,240.80,8.60,0.50
min,2.00,18.00,1.00,1.00,0.00,0.00,100.00,1.00,0.00
25%,113621.75,29.00,16.00,9.00,1.00,6.00,480.00,7.00,0.00
50%,226125.50,39.00,32.00,16.00,3.00,12.00,661.00,14.00,1.00
75%,337739.25,48.00,46.00,23.00,6.00,19.00,830.00,22.00,1.00
max,449999.00,65.00,60.00,30.00,10.00,30.00,1000.00,30.00,1.00

***Task-1*** NORMALIZATION

In [12]:
df.head(10)

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0
5,8.0,51.0,Male,33.0,25.0,9.0,26.0,Premium,Annual,129.0,8.0,1.0
6,9.0,58.0,Female,49.0,12.0,3.0,16.0,Standard,Quarterly,821.0,24.0,1.0
7,10.0,55.0,Female,37.0,8.0,4.0,15.0,Premium,Annual,445.0,30.0,1.0
8,11.0,39.0,Male,12.0,5.0,7.0,4.0,Standard,Quarterly,969.0,13.0,1.0
9,12.0,64.0,Female,3.0,25.0,2.0,11.0,Standard,Quarterly,415.0,29.0,1.0

In [13]:
new_df = pd.DataFrame(df,columns = ['Age', 'Total Spend'])

In [14]:
new_df.head(5)

    Age  Total Spend
0  30.0        932.0
1  65.0        557.0
2  55.0        185.0
3  58.0        396.0
4  23.0        617.0

In [15]:
new_df['Age']=new_df['Age'].fillna(new_df['Age'].mean())

In [16]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Age          440833 non-null  float64
 1   Total Spend  440832 non-null  float64
dtypes: float64(2)
memory usage: 6.7 MB

In [17]:
scaler = MinMaxScaler() # Instantiating the MinMaxScaler() function
normalized_df = scaler.fit_transform(new_df)
print(normalized_df)

[[0.25531915 0.92444444]
 [1.         0.50777778]
 [0.78723404 0.09444444]
 ...
 [0.17021277 0.97478889]
 [0.21276596 0.55838889]
 [0.27659574 0.51974444]]

### Example

In [22]:
x_array = np.array([[120],[150],[200],[250],[300],[350],[400],[450],[500],[550]])

scaler = MinMaxScaler()
normalized_arr = scaler.fit_transform(x_array)

print(normalized_arr)

[[0.        ]
 [0.06976744]
 [0.18604651]
 [0.30232558]
 [0.41860465]
 [0.53488372]
 [0.65116279]
 [0.76744186]
 [0.88372093]
 [1.        ]]

***Task-2***
STANDARDIZATION

In [21]:
scaler = StandardScaler()
standardized_df = scaler.fit_transform(new_df)
print(standardized_df)

[[-0.75332715  1.2474268 ]
 [ 2.05964826 -0.30986452]
 [ 1.255941   -1.85469752]
 ...
 [-1.07481005  1.43558912]
 [-0.9140686  -0.12070554]
 [-0.67295642 -0.26513912]]

### Example 2

In [24]:
x_array = np.array([[120],[150],[200],[250],[300],[350],[400],[450],[500],[550]])

scaler = StandardScaler()
normalized_arr_ss = scaler.fit_transform(x_array)
print(normalized_arr_ss)

[[-1.47253588]
 [-1.25912488]
 [-0.90343989]
 [-0.54775489]
 [-0.1920699 ]
 [ 0.1636151 ]
 [ 0.51930009]
 [ 0.87498509]
 [ 1.23067009]
 [ 1.58635508]]